
steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'Write-Host "This is me running PowerShell code!"'
      pwsh: true

  - task: PublishPipelineArtifact@1
    inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'WebApp'
